window.TRANSLATIONS = {
  // Navigation
  "nav.home": { en:"Home", ja:"ホーム", ar:"الرئيسية", ko:"홈", zh:"首页", nl:"Home", de:"Startseite", fr:"Accueil", es:"Inicio", ru:"Главная", tr:"Ana Sayfa", it:"Home" },
  "nav.products": { en:"Products", ja:"製品", ar:"المنتجات", ko:"제품", zh:"产品", nl:"Producten", de:"Produkte", fr:"Produits", es:"Productos", ru:"Продукция", tr:"Ürünler", it:"Prodotti" },
  "nav.mix": { en:"Mix Your Blend", ja:"ブレンド配合", ar:"امزج خلطتك", ko:"블렌드 배합", zh:"混合配比", nl:"Mix Uw Blend", de:"Mischung erstellen", fr:"Créez Votre Mélange", es:"Mezcla Tu Blend", ru:"Создайте Смесь", tr:"Karışımınızı Oluşturun", it:"Crea il Tuo Mix" },
  "nav.about": { en:"About", ja:"会社概要", ar:"من نحن", ko:"회사소개", zh:"关于我们", nl:"Over Ons", de:"Über Uns", fr:"À Propos", es:"Nosotros", ru:"О Нас", tr:"Hakkımızda", it:"Chi Siamo" },
  "nav.gallery": { en:"Gallery", ja:"ギャラリー", ar:"معرض الصور", ko:"갤러리", zh:"图库", nl:"Galerij", de:"Galerie", fr:"Galerie", es:"Galería", ru:"Галерея", tr:"Galeri", it:"Galleria" },
  "nav.quality": { en:"Quality", ja:"品質", ar:"الجودة", ko:"품질", zh:"质量", nl:"Kwaliteit", de:"Qualität", fr:"Qualité", es:"Calidad", ru:"Качество", tr:"Kalite", it:"Qualità" },
  "nav.knowledge": { en:"Knowledge", ja:"知識", ar:"المعرفة", ko:"지식센터", zh:"知识中心", nl:"Kennis", de:"Wissen", fr:"Savoir", es:"Conocimiento", ru:"Знания", tr:"Bilgi", it:"Conoscenza" },
  "nav.contact": { en:"Get in Touch", ja:"お問い合わせ", ar:"تواصل معنا", ko:"문의하기", zh:"联系我们", nl:"Contact", de:"Kontakt", fr:"Contactez-Nous", es:"Contáctenos", ru:"Связаться", tr:"İletişim", it:"Contattaci" },

  // Hero
  "hero.label": { en:"From the heart of Sri Lanka", ja:"スリランカの中心から", ar:"من قلب سريلانكا", ko:"스리랑카의 심장에서", zh:"来自斯里兰卡的心脏地带", nl:"Uit het hart van Sri Lanka", de:"Aus dem Herzen Sri Lankas", fr:"Du cœur du Sri Lanka", es:"Desde el corazón de Sri Lanka", ru:"Из сердца Шри-Ланки", tr:"Sri Lanka'nın kalbinden", it:"Dal cuore dello Sri Lanka" },
  "hero.title1": { en:"Premium Coir", ja:"プレミアム", ar:"ركائز جوز الهند", ko:"프리미엄 코이어", zh:"优质椰糠", nl:"Premium Kokos", de:"Premium Kokos", fr:"Substrats de Coco", es:"Sustratos de Coco", ru:"Премиум Кокосовые", tr:"Premium Hindistancevizi", it:"Substrati di Cocco" },
  "hero.title2": { en:"Substrates for", ja:"コイアー基材", ar:"الممتازة من أجل", ko:"기질, 글로벌", zh:"基质，助力", nl:"Substraten voor", de:"Substrate für", fr:"Premium pour une", es:"Premium para un", ru:"Субстраты для", tr:"Substratları,", it:"Premium per una" },
  "hero.title3": { en:"Global Growth", ja:"世界の成長へ", ar:"النمو العالمي", ko:"성장을 위해", zh:"全球增长", nl:"Wereldwijde Groei", de:"Globales Wachstum", fr:"Croissance Mondiale", es:"Crecimiento Global", ru:"Глобального Роста", tr:"Küresel Büyüme", it:"Crescita Globale" },
  "hero.desc": { en:"Sustainably sourced from Tangalle's coconut groves, our cocopeat and coir products deliver exceptional quality for horticulture, agriculture, and beyond.", ja:"タンガレのココナッツ林から持続可能に調達。園芸、農業などに卓越した品質のココピートとコイア製品をお届けします。", ar:"مصدرها المستدام من بساتين جوز الهند في تانجالي، منتجاتنا من الكوكوبيت والكوير توفر جودة استثنائية للبستنة والزراعة.", ko:"탕갈레의 코코넛 농장에서 지속 가능하게 조달한 코코피트와 코이어 제품은 원예, 농업 등에 탁월한 품질을 제공합니다.", zh:"从坦加勒的椰子林可持续采购，我们的椰糠和椰壳纤维产品为园艺、农业等领域提供卓越品质。", nl:"Duurzaam gewonnen uit de kokospalmen van Tangalle. Onze cocopeat- en kokosproducten leveren uitzonderlijke kwaliteit voor tuinbouw en landbouw.", de:"Nachhaltig aus Tangalles Kokoshainen gewonnen. Unsere Kokosfaser-Produkte liefern außergewöhnliche Qualität für Gartenbau und Landwirtschaft.", fr:"Issus des cocoteraies de Tangalle de manière durable, nos produits de coco offrent une qualité exceptionnelle pour l'horticulture et l'agriculture.", es:"Obtenidos de forma sostenible de los cocotales de Tangalle, nuestros productos de coco ofrecen calidad excepcional para horticultura y agricultura.", ru:"Устойчиво добываемые из кокосовых рощ Тангалле, наши кокосовые субстраты обеспечивают исключительное качество для садоводства и сельского хозяйства.", tr:"Tangalle'nin hindistancevizi bahçelerinden sürdürülebilir şekilde temin edilen ürünlerimiz, bahçecilik ve tarım için olağanüstü kalite sunar.", it:"Provenienti in modo sostenibile dai palmeti di Tangalle, i nostri prodotti in fibra di cocco offrono qualità eccezionale per orticoltura e agricoltura." },
  "hero.cta1": { en:"Explore Products", ja:"製品を見る", ar:"اكتشف المنتجات", ko:"제품 살펴보기", zh:"探索产品", nl:"Bekijk Producten", de:"Produkte Entdecken", fr:"Découvrir les Produits", es:"Explorar Productos", ru:"Смотреть Продукцию", tr:"Ürünleri Keşfet", it:"Esplora i Prodotti" },
  "hero.cta2": { en:"Our Story", ja:"私たちの物語", ar:"قصتنا", ko:"우리의 이야기", zh:"我们的故事", nl:"Ons Verhaal", de:"Unsere Geschichte", fr:"Notre Histoire", es:"Nuestra Historia", ru:"Наша История", tr:"Hikayemiz", it:"La Nostra Storia" },

  // Trust bar
  "trust.label": { en:"Trusted worldwide", ja:"世界中で信頼", ar:"موثوق عالمياً", ko:"전 세계 신뢰", zh:"全球信赖", nl:"Wereldwijd vertrouwd", de:"Weltweit vertraut", fr:"Confiance mondiale", es:"Confianza mundial", ru:"Доверие по всему миру", tr:"Dünya çapında güvenilir", it:"Affidabilità mondiale" },
  "trust.countries": { en:"Countries", ja:"ヶ国", ar:"دولة", ko:"개국", zh:"个国家", nl:"Landen", de:"Länder", fr:"Pays", es:"Países", ru:"Стран", tr:"Ülke", it:"Paesi" },
  "trust.natural": { en:"Natural", ja:"天然", ar:"طبيعي", ko:"천연", zh:"天然", nl:"Natuurlijk", de:"Natürlich", fr:"Naturel", es:"Natural", ru:"Натуральный", tr:"Doğal", it:"Naturale" },
  "trust.certified": { en:"Certified", ja:"認証済み", ar:"معتمد", ko:"인증", zh:"认证", nl:"Gecertificeerd", de:"Zertifiziert", fr:"Certifié", es:"Certificado", ru:"Сертифицировано", tr:"Sertifikalı", it:"Certificato" },
  "trust.eco": { en:"Friendly", ja:"エコ対応", ar:"صديق للبيئة", ko:"친환경", zh:"环保", nl:"Vriendelijk", de:"Freundlich", fr:"Écologique", es:"Ecológico", ru:"Экологичный", tr:"Dostu", it:"Ecologico" },

  // Products section
  "products.label": { en:"Our Products", ja:"製品紹介", ar:"منتجاتنا", ko:"제품 소개", zh:"我们的产品", nl:"Onze Producten", de:"Unsere Produkte", fr:"Nos Produits", es:"Nuestros Productos", ru:"Наша Продукция", tr:"Ürünlerimiz", it:"I Nostri Prodotti" },
  "products.title1": { en:"Nature's Finest", ja:"最高品質の", ar:"أجود ما في الطبيعة", ko:"자연 최고의", zh:"自然之选", nl:"Het Finest van de Natuur", de:"Das Beste der Natur", fr:"Le Meilleur de la Nature", es:"Lo Mejor de la Naturaleza", ru:"Лучшее от Природы", tr:"Doğanın En İyisi", it:"Il Meglio della Natura" },
  "products.title2": { en:"Growing Medium", ja:"栽培基材", ar:"وسط النمو", ko:"재배 매체", zh:"种植介质", nl:"Groeimedium", de:"Wachstumsmedium", fr:"Substrat de Culture", es:"Medio de Cultivo", ru:"Среда для Выращивания", tr:"Yetiştirme Ortamı", it:"Substrato di Coltivazione" },
  "products.desc": { en:"Each product is carefully processed from premium Sri Lankan coconut husks to meet the highest international standards.", ja:"各製品はスリランカの最高級ココナッツ殻から丁寧に加工され、最高水準の国際基準を満たしています。", ar:"يتم معالجة كل منتج بعناية من قشور جوز الهند السريلانكية الممتازة لتلبية أعلى المعايير الدولية.", ko:"각 제품은 프리미엄 스리랑카 코코넛 껍질에서 정성스럽게 가공되어 최고 국제 기준을 충족합니다.", zh:"每件产品均由优质斯里兰卡椰子壳精心加工，满足最高国际标准。", nl:"Elk product wordt zorgvuldig verwerkt uit premium Sri Lankaanse kokosnootschillen.", de:"Jedes Produkt wird sorgfältig aus erstklassigen sri-lankischen Kokosnussschalen verarbeitet.", fr:"Chaque produit est soigneusement traité à partir de coques de noix de coco sri-lankaises premium.", es:"Cada producto es cuidadosamente procesado a partir de cáscaras de coco premium de Sri Lanka.", ru:"Каждый продукт тщательно изготовлен из кокосовой скорлупы премиум-класса из Шри-Ланки.", tr:"Her ürün, birinci sınıf Sri Lanka hindistancevizi kabuklarından özenle işlenir.", it:"Ogni prodotto è accuratamente lavorato da gusci di cocco premium dello Sri Lanka." },
  "products.cocopeat": { en:"Cocopeat", ja:"ココピート", ar:"كوكوبيت", ko:"코코피트", zh:"椰糠", nl:"Cocopeat", de:"Kokosfasertorf", fr:"Tourbe de Coco", es:"Fibra de Coco", ru:"Кокосовый торф", tr:"Kokopit", it:"Torba di Cocco" },
  "products.cocochips": { en:"Cocochips", ja:"ココチップ", ar:"رقائق جوز الهند", ko:"코코칩", zh:"椰壳片", nl:"Cocochips", de:"Kokoschips", fr:"Chips de Coco", es:"Chips de Coco", ru:"Кокосовые чипсы", tr:"Kokos Cipsleri", it:"Chips di Cocco" },
  "products.blocks": { en:"5kg Blocks", ja:"5kgブロック", ar:"كتل 5 كجم", ko:"5kg 블록", zh:"5公斤压缩块", nl:"5kg Blokken", de:"5kg Blöcke", fr:"Blocs de 5kg", es:"Bloques de 5kg", ru:"Блоки 5кг", tr:"5kg Bloklar", it:"Blocchi da 5kg" },
  "products.growbags": { en:"Grow Bags", ja:"グローバッグ", ar:"أكياس النمو", ko:"그로우백", zh:"种植袋", nl:"Kweekzakken", de:"Pflanzsäcke", fr:"Sacs de Culture", es:"Bolsas de Cultivo", ru:"Мешки для выращивания", tr:"Yetiştirme Torbaları", it:"Sacchi di Coltivazione" },
  "products.learnmore": { en:"Learn More", ja:"詳しく見る", ar:"اعرف المزيد", ko:"자세히 보기", zh:"了解更多", nl:"Meer Info", de:"Mehr Erfahren", fr:"En Savoir Plus", es:"Saber Más", ru:"Подробнее", tr:"Daha Fazla", it:"Scopri di Più" },
  "products.bestseller": { en:"Bestseller", ja:"ベストセラー", ar:"الأكثر مبيعاً", ko:"베스트셀러", zh:"畅销产品", nl:"Bestseller", de:"Bestseller", fr:"Meilleures Ventes", es:"Más Vendido", ru:"Бестселлер", tr:"En Çok Satan", it:"Più Venduto" },

  // About
  "about.label": { en:"Why Ceylon Substrates", ja:"セイロンサブストレーツを選ぶ理由", ar:"لماذا سيلون سبستريتس", ko:"실론 서브스트레이트를 선택하는 이유", zh:"为什么选择锡兰基质", nl:"Waarom Ceylon Substrates", de:"Warum Ceylon Substrates", fr:"Pourquoi Ceylon Substrates", es:"Por qué Ceylon Substrates", ru:"Почему Ceylon Substrates", tr:"Neden Ceylon Substrates", it:"Perché Ceylon Substrates" },
  "about.title1": { en:"Rooted in", ja:"根ざした", ar:"متجذرون في", ko:"뿌리 깊은", zh:"根植于", nl:"Geworteld in", de:"Verwurzelt in", fr:"Enraciné dans l'", es:"Arraigados en la", ru:"Корнями в", tr:"Kökleri", it:"Radicati nell'" },
  "about.title2": { en:"Excellence", ja:"卓越性", ar:"التميّز", ko:"탁월함", zh:"卓越", nl:"Excellentie", de:"Exzellenz", fr:"Excellence", es:"Excelencia", ru:"Совершенство", tr:"Mükemmellik", it:"Eccellenza" },
  "about.sustainable": { en:"Sustainably Sourced", ja:"持続可能な調達", ar:"مصادر مستدامة", ko:"지속가능한 조달", zh:"可持续采购", nl:"Duurzaam Ingekocht", de:"Nachhaltig Beschafft", fr:"Approvisionnement Durable", es:"Abastecimiento Sostenible", ru:"Устойчивые Источники", tr:"Sürdürülebilir Kaynak", it:"Approvvigionamento Sostenibile" },
  "about.quality": { en:"Quality Controlled", ja:"品質管理", ar:"مراقبة الجودة", ko:"품질 관리", zh:"质量控制", nl:"Kwaliteitscontrole", de:"Qualitätskontrolliert", fr:"Contrôle Qualité", es:"Control de Calidad", ru:"Контроль Качества", tr:"Kalite Kontrollü", it:"Controllo Qualità" },
  "about.delivery": { en:"Global Delivery", ja:"グローバル配送", ar:"توصيل عالمي", ko:"글로벌 배송", zh:"全球配送", nl:"Wereldwijde Levering", de:"Weltweite Lieferung", fr:"Livraison Mondiale", es:"Entrega Global", ru:"Мировая Доставка", tr:"Küresel Teslimat", it:"Consegna Globale" },

  // CTA
  "cta.title1": { en:"Ready to Grow with", ja:"一緒に成長しませんか", ar:"مستعد للنمو مع", ko:"함께 성장할 준비가 되셨나요", zh:"准备好与", nl:"Klaar om te Groeien met", de:"Bereit zu Wachsen mit", fr:"Prêt à Grandir avec", es:"Listo para Crecer con", ru:"Готовы Расти с", tr:"Büyümeye Hazır mısınız", it:"Pronti a Crescere con" },
  "cta.title2": { en:"Ceylon?", ja:"セイロンと", ar:"سيلون؟", ko:"실론?", zh:"锡兰一起成长？", nl:"Ceylon?", de:"Ceylon?", fr:"Ceylon?", es:"Ceylon?", ru:"Цейлоном?", tr:"Ceylon ile?", it:"Ceylon?" },
  "cta.quote": { en:"Request a Quote", ja:"見積もりを依頼", ar:"اطلب عرض سعر", ko:"견적 요청", zh:"请求报价", nl:"Offerte Aanvragen", de:"Angebot Anfordern", fr:"Demander un Devis", es:"Solicitar Cotización", ru:"Запросить Цену", tr:"Teklif İste", it:"Richiedi un Preventivo" },
  "cta.email": { en:"Email Us", ja:"メールする", ar:"راسلنا", ko:"이메일 보내기", zh:"发送邮件", nl:"E-mail Ons", de:"E-Mail Senden", fr:"Envoyez un Email", es:"Envíenos un Email", ru:"Написать Нам", tr:"Bize E-posta Gönderin", it:"Inviaci un'Email" },

  // Contact
  "contact.label": { en:"Contact", ja:"お問い合わせ", ar:"اتصل بنا", ko:"연락처", zh:"联系方式", nl:"Contact", de:"Kontakt", fr:"Contact", es:"Contacto", ru:"Контакты", tr:"İletişim", it:"Contatti" },
  "contact.title1": { en:"Let's Start a", ja:"始めましょう", ar:"لنبدأ", ko:"대화를 시작합시다", zh:"开始一段", nl:"Laten We een", de:"Lassen Sie uns ein", fr:"Commençons une", es:"Comencemos una", ru:"Давайте Начнём", tr:"Bir Sohbet", it:"Iniziamo una" },
  "contact.title2": { en:"Conversation", ja:"会話を", ar:"محادثة", ko:"", zh:"对话", nl:"Gesprek Beginnen", de:"Gespräch Beginnen", fr:"Conversation", es:"Conversación", ru:"Разговор", tr:"Başlatalım", it:"Conversazione" },
  "contact.send": { en:"Send Inquiry", ja:"お問い合わせを送信", ar:"إرسال استفسار", ko:"문의 보내기", zh:"发送询价", nl:"Vraag Versturen", de:"Anfrage Senden", fr:"Envoyer une Demande", es:"Enviar Consulta", ru:"Отправить Запрос", tr:"Sorgu Gönder", it:"Invia Richiesta" },

  // Footer
  "footer.rights": { en:"All rights reserved.", ja:"全著作権所有。", ar:"جميع الحقوق محفوظة.", ko:"모든 권리 보유.", zh:"版权所有。", nl:"Alle rechten voorbehouden.", de:"Alle Rechte vorbehalten.", fr:"Tous droits réservés.", es:"Todos los derechos reservados.", ru:"Все права защищены.", tr:"Tüm hakları saklıdır.", it:"Tutti i diritti riservati." },

  // Language names for selector
  "_lang.en": "English",
  "_lang.ja": "日本語",
  "_lang.ar": "العربية",
  "_lang.ko": "한국어",
  "_lang.zh": "中文",
  "_lang.nl": "Nederlands",
  "_lang.de": "Deutsch",
  "_lang.fr": "Français",
  "_lang.es": "Español",
  "_lang.ru": "Русский",
  "_lang.tr": "Türkçe",
  "_lang.it": "Italiano",

  // Greenhouse Banner
  "banner.label": { en:"Modern Greenhouse Solutions", ja:"最新の温室ソリューション", ar:"حلول الدفيئة الحديثة", ko:"현대 온실 솔루션", zh:"现代温室解决方案", nl:"Moderne Kasoplossingen", de:"Moderne Gewächshauslösungen", fr:"Solutions de Serre Modernes", es:"Soluciones de Invernadero Modernas", ru:"Современные Тепличные Решения", tr:"Modern Sera Çözümleri", it:"Soluzioni Serra Moderne" },
  "banner.title": { en:"Grow Bags Built for", ja:"性能のために作られた", ar:"أكياس نمو مصممة من أجل", ko:"성능을 위해 제작된", zh:"为性能而生的", nl:"Kweekzakken Gebouwd voor", de:"Pflanzsäcke für", fr:"Sacs de Culture Conçus pour la", es:"Bolsas de Cultivo para", ru:"Мешки для Выращивания для", tr:"Performans İçin Üretilen", it:"Sacchi da Coltivazione per" },
  "banner.title2": { en:"Performance", ja:"グローバッグ", ar:"الأداء", ko:"그로우백", zh:"种植袋", nl:"Prestaties", de:"Leistung Gebaut", fr:"Performance", es:"Rendimiento", ru:"Производительности", tr:"Yetiştirme Torbaları", it:"Prestazioni" },
  "banner.desc": { en:"Our cocopeat grow bags are engineered for modern greenhouse operations — optimized drainage, UV-stabilized packaging, and custom blends for maximum yield.", ja:"当社のココピートグローバッグは最新の温室運営向けに設計されています。最適な排水性、UV安定化パッケージ、最大収量のためのカスタムブレンド。", ar:"أكياس النمو لدينا مصممة لعمليات الدفيئة الحديثة - تصريف محسّن وتغليف مستقر ضد الأشعة فوق البنفسجية وخلطات مخصصة لأقصى إنتاجية.", ko:"당사의 코코피트 그로우백은 최적화된 배수, UV 안정화 포장, 최대 수확량을 위한 맞춤 배합으로 현대 온실 운영에 맞게 설계되었습니다.", zh:"我们的椰糠种植袋专为现代温室运营设计——优化排水、UV稳定包装和最大产量的定制配比。", nl:"Onze cocopeat kweekzakken zijn ontworpen voor moderne kasoperaties — geoptimaliseerde drainage, UV-gestabiliseerde verpakking en aangepaste mengsels.", de:"Unsere Kokosfaser-Pflanzsäcke sind für moderne Gewächshausbetriebe konzipiert — optimierte Entwässerung, UV-stabilisierte Verpackung und individuelle Mischungen.", fr:"Nos sacs de culture en coco sont conçus pour les serres modernes — drainage optimisé, emballage stabilisé aux UV et mélanges personnalisés.", es:"Nuestras bolsas de cultivo de coco están diseñadas para invernaderos modernos — drenaje optimizado, embalaje estabilizado UV y mezclas personalizadas.", ru:"Наши мешки для выращивания из кокосового волокна разработаны для современных тепличных операций — оптимизированный дренаж, UV-стабилизированная упаковка и индивидуальные смеси.", tr:"Kokopit yetiştirme torbalarımız modern sera operasyonları için tasarlanmıştır — optimize edilmiş drenaj, UV stabilize ambalaj ve maksimum verim için özel karışımlar.", it:"I nostri sacchi di coltivazione in cocco sono progettati per le serre moderne — drenaggio ottimizzato, imballaggio stabilizzato UV e miscele personalizzate." },
  "banner.cta": { en:"View Grow Bags", ja:"グローバッグを見る", ar:"عرض أكياس النمو", ko:"그로우백 보기", zh:"查看种植袋", nl:"Bekijk Kweekzakken", de:"Pflanzsäcke Ansehen", fr:"Voir les Sacs", es:"Ver Bolsas", ru:"Смотреть Мешки", tr:"Torbaları Görüntüle", it:"Vedi Sacchi" },

  // About section descriptions
  "about.desc": { en:"Based in Tangalle on Sri Lanka's southern coast, we source the finest coconut husks from surrounding groves. Every product is processed with precision to deliver consistent quality that growers worldwide depend on.", ja:"スリランカ南海岸のタンガレに拠点を置き、周辺の農園から最高級のココナッツ殻を調達。すべての製品は精密に加工され、世界中の生産者が信頼する一貫した品質をお届けします。", ar:"مقرنا في تانجالي على الساحل الجنوبي لسريلانكا، نحصل على أجود قشور جوز الهند من البساتين المحيطة. يتم معالجة كل منتج بدقة لتقديم جودة ثابتة يعتمد عليها المزارعون في جميع أنحاء العالم.", ko:"스리랑카 남부 해안의 탕갈레에 본사를 두고 주변 농장에서 최상급 코코넛 껍질을 조달합니다. 모든 제품은 전 세계 재배자들이 신뢰하는 일관된 품질을 제공하기 위해 정밀하게 가공됩니다.", zh:"总部位于斯里兰卡南海岸的坦加勒，我们从周边椰子林采购最优质的椰子壳。每件产品都经过精密加工，为全球种植者提供始终如一的品质。", nl:"Gevestigd in Tangalle aan de zuidkust van Sri Lanka, betrekken wij de finest kokosnootschillen uit omliggende plantages.", de:"Mit Sitz in Tangalle an der Südküste Sri Lankas beziehen wir die feinsten Kokosnussschalen aus umliegenden Plantagen.", fr:"Basés à Tangalle sur la côte sud du Sri Lanka, nous nous approvisionnons en coques de noix de coco premium auprès des plantations environnantes.", es:"Con sede en Tangalle, en la costa sur de Sri Lanka, obtenemos las mejores cáscaras de coco de las plantaciones circundantes.", ru:"Расположенные в Тангалле на южном побережье Шри-Ланки, мы закупаем лучшую кокосовую скорлупу из окружающих рощ.", tr:"Sri Lanka'nın güney kıyısındaki Tangalle'de bulunan şirketimiz, çevredeki bahçelerden en kaliteli hindistancevizi kabuklarını temin eder.", it:"Con sede a Tangalle sulla costa meridionale dello Sri Lanka, ci approvvigioniamo dei migliori gusci di cocco dalle piantagioni circostanti." },
  "about.sustainable.desc": { en:"100% natural coconut by-product, processed without chemicals.", ja:"100%天然のココナッツ副産物、化学物質不使用で加工。", ar:"منتج ثانوي طبيعي 100% من جوز الهند، معالج بدون مواد كيميائية.", ko:"100% 천연 코코넛 부산물, 화학물질 없이 가공.", zh:"100%天然椰子副产品，无化学加工。", nl:"100% natuurlijk kokosnevenproduct, verwerkt zonder chemicaliën.", de:"100% natürliches Kokos-Nebenprodukt, ohne Chemikalien verarbeitet.", fr:"Sous-produit de noix de coco 100% naturel, traité sans produits chimiques.", es:"Subproducto de coco 100% natural, procesado sin químicos.", ru:"100% натуральный побочный продукт кокоса, обработанный без химикатов.", tr:"100% doğal hindistancevizi yan ürünü, kimyasal madde kullanılmadan işlenmiştir.", it:"Sottoprodotto di cocco 100% naturale, lavorato senza sostanze chimiche." },
  "about.quality.desc": { en:"Rigorous testing for EC, pH, and moisture content on every batch.", ja:"すべてのバッチでEC、pH、水分含有量の厳密なテスト。", ar:"اختبارات صارمة للموصلية الكهربائية ودرجة الحموضة ومحتوى الرطوبة في كل دفعة.", ko:"모든 배치에 대한 EC, pH 및 수분 함량의 엄격한 테스트.", zh:"每批次严格测试EC、pH和含水量。", nl:"Strenge tests op EC, pH en vochtgehalte bij elke batch.", de:"Strenge Prüfung von EC, pH und Feuchtigkeitsgehalt bei jeder Charge.", fr:"Tests rigoureux d'EC, pH et teneur en humidité sur chaque lot.", es:"Pruebas rigurosas de CE, pH y contenido de humedad en cada lote.", ru:"Строгие испытания ЕС, pH и влажности каждой партии.", tr:"Her partide EC, pH ve nem içeriği için titiz testler.", it:"Test rigorosi di EC, pH e contenuto di umidità su ogni lotto." },
  "about.delivery.desc": { en:"Reliable container shipping to Europe, USA, Asia, and the Middle East.", ja:"ヨーロッパ、アメリカ、アジア、中東への信頼性の高いコンテナ輸送。", ar:"شحن حاويات موثوق إلى أوروبا والولايات المتحدة وآسيا والشرق الأوسط.", ko:"유럽, 미국, 아시아, 중동으로의 안정적인 컨테이너 배송.", zh:"可靠的集装箱运输至欧洲、美国、亚洲和中东。", nl:"Betrouwbare containerverscheping naar Europa, VS, Azië en het Midden-Oosten.", de:"Zuverlässiger Containerversand nach Europa, USA, Asien und den Nahen Osten.", fr:"Expédition fiable de conteneurs vers l'Europe, les USA, l'Asie et le Moyen-Orient.", es:"Envío confiable de contenedores a Europa, EE.UU., Asia y Medio Oriente.", ru:"Надёжная контейнерная доставка в Европу, США, Азию и Ближний Восток.", tr:"Avrupa, ABD, Asya ve Orta Doğu'ya güvenilir konteyner sevkiyatı.", it:"Spedizione affidabile di container in Europa, USA, Asia e Medio Oriente." },

  // Certifications
  "cert.label": { en:"Certifications", ja:"認証", ar:"الشهادات", ko:"인증", zh:"认证", nl:"Certificeringen", de:"Zertifizierungen", fr:"Certifications", es:"Certificaciones", ru:"Сертификаты", tr:"Sertifikalar", it:"Certificazioni" },
  "cert.title": { en:"Quality You Can", ja:"信頼できる", ar:"جودة يمكنك", ko:"신뢰할 수 있는", zh:"值得信赖的", nl:"Kwaliteit die U Kunt", de:"Qualität der Sie", fr:"Qualité en Laquelle Vous Pouvez Avoir", es:"Calidad en la que Puede", ru:"Качество, Которому Можно", tr:"Güvenebileceğiniz", it:"Qualità di Cui Puoi" },
  "cert.title2": { en:"Trust", ja:"品質", ar:"الوثوق بها", ko:"품질", zh:"质量", nl:"Vertrouwen", de:"Vertrauen Können", fr:"Confiance", es:"Confiar", ru:"Доверять", tr:"Kalite", it:"Fidarti" },

  // Process
  "process.label": { en:"Our Process", ja:"製造工程", ar:"عمليتنا", ko:"제조 공정", zh:"生产工艺", nl:"Ons Proces", de:"Unser Prozess", fr:"Notre Processus", es:"Nuestro Proceso", ru:"Наш Процесс", tr:"Sürecimiz", it:"Il Nostro Processo" },
  "process.title": { en:"From Husk to", ja:"殻から", ar:"من القشرة إلى", ko:"껍질에서", zh:"从壳到", nl:"Van Schil tot", de:"Von der Schale zur", fr:"De la Coque à la", es:"De la Cáscara a la", ru:"От Скорлупы до", tr:"Kabuktan", it:"Dal Guscio al" },
  "process.title2": { en:"Harvest", ja:"収穫まで", ar:"الحصاد", ko:"수확까지", zh:"丰收", nl:"Oogst", de:"Ernte", fr:"Récolte", es:"Cosecha", ru:"Урожая", tr:"Hasata", it:"Raccolto" },
  "process.step1": { en:"Sourcing", ja:"原料調達", ar:"التوريد", ko:"원료 조달", zh:"原料采购", nl:"Inkoop", de:"Beschaffung", fr:"Approvisionnement", es:"Abastecimiento", ru:"Закупка", tr:"Tedarik", it:"Approvvigionamento" },
  "process.step1.desc": { en:"Fresh coconut husks collected from local groves in southern Sri Lanka.", ja:"スリランカ南部の地元農園から新鮮なココナッツ殻を収集。", ar:"جمع قشور جوز الهند الطازجة من البساتين المحلية في جنوب سريلانكا.", ko:"스리랑카 남부 지역 농장에서 신선한 코코넛 껍질을 수집.", zh:"从斯里兰卡南部当地椰子林收集新鲜椰子壳。", nl:"Verse kokosnootschillen verzameld uit lokale plantages in Zuid-Sri Lanka.", de:"Frische Kokosnussschalen aus lokalen Plantagen in Süd-Sri Lanka.", fr:"Coques de noix de coco fraîches collectées dans les plantations locales du sud du Sri Lanka.", es:"Cáscaras de coco frescas recolectadas de plantaciones locales del sur de Sri Lanka.", ru:"Свежая кокосовая скорлупа, собранная с местных плантаций на юге Шри-Ланки.", tr:"Sri Lanka'nın güneyindeki yerel bahçelerden taze hindistancevizi kabukları toplanır.", it:"Gusci di cocco freschi raccolti dalle piantagioni locali nel sud dello Sri Lanka." },
  "process.step2": { en:"Processing", ja:"加工", ar:"المعالجة", ko:"가공", zh:"加工", nl:"Verwerking", de:"Verarbeitung", fr:"Traitement", es:"Procesamiento", ru:"Обработка", tr:"İşleme", it:"Lavorazione" },
  "process.step2.desc": { en:"Husks are shredded, washed, and separated into peat and chips.", ja:"殻を粉砕、洗浄し、ピートとチップに分離。", ar:"يتم تقطيع القشور وغسلها وفصلها إلى خث ورقائق.", ko:"껍질을 파쇄, 세척하여 피트와 칩으로 분리.", zh:"椰壳经粉碎、清洗后分离成椰糠和椰壳片。", nl:"Schillen worden versnipperd, gewassen en gescheiden in turf en chips.", de:"Schalen werden zerkleinert, gewaschen und in Torf und Chips getrennt.", fr:"Les coques sont broyées, lavées et séparées en tourbe et chips.", es:"Las cáscaras se trituran, lavan y separan en turba y chips.", ru:"Скорлупа измельчается, промывается и разделяется на торф и чипсы.", tr:"Kabuklar parçalanır, yıkanır ve torf ile cips olarak ayrılır.", it:"I gusci vengono triturati, lavati e separati in torba e chips." },
  "process.step3": { en:"Quality Check", ja:"品質検査", ar:"فحص الجودة", ko:"품질 검사", zh:"质量检测", nl:"Kwaliteitscontrole", de:"Qualitätsprüfung", fr:"Contrôle Qualité", es:"Control de Calidad", ru:"Контроль Качества", tr:"Kalite Kontrolü", it:"Controllo Qualità" },
  "process.step3.desc": { en:"Every batch tested for EC, pH, moisture, and fibre content.", ja:"すべてのバッチでEC、pH、水分、繊維含有量をテスト。", ar:"يتم اختبار كل دفعة للموصلية الكهربائية ودرجة الحموضة والرطوبة ومحتوى الألياف.", ko:"모든 배치에 대해 EC, pH, 수분 및 섬유 함량 테스트.", zh:"每批次检测EC、pH、含水量和纤维含量。", nl:"Elke batch getest op EC, pH, vocht en vezelgehalte.", de:"Jede Charge auf EC, pH, Feuchtigkeit und Fasergehalt getestet.", fr:"Chaque lot testé pour l'EC, le pH, l'humidité et la teneur en fibres.", es:"Cada lote probado para CE, pH, humedad y contenido de fibra.", ru:"Каждая партия проверяется на ЕС, pH, влажность и содержание волокон.", tr:"Her parti EC, pH, nem ve lif içeriği açısından test edilir.", it:"Ogni lotto testato per EC, pH, umidità e contenuto di fibre." },
  "process.step4": { en:"Export", ja:"輸出", ar:"التصدير", ko:"수출", zh:"出口", nl:"Export", de:"Export", fr:"Exportation", es:"Exportación", ru:"Экспорт", tr:"İhracat", it:"Esportazione" },
  "process.step4.desc": { en:"Compressed, packed, and shipped worldwide from Hambantota Port.", ja:"圧縮、梱包し、ハンバントタ港から世界中に出荷。", ar:"مضغوطة ومعبأة وشحنها في جميع أنحاء العالم من ميناء هامبانتوتا.", ko:"압축, 포장하여 함반토타 항구에서 전 세계로 배송.", zh:"压缩、包装，从汉班托塔港运往全球。", nl:"Gecomprimeerd, verpakt en wereldwijd verscheept vanuit de haven van Hambantota.", de:"Komprimiert, verpackt und weltweit vom Hafen Hambantota verschickt.", fr:"Comprimés, emballés et expédiés dans le monde entier depuis le port de Hambantota.", es:"Comprimidos, empacados y enviados a todo el mundo desde el Puerto de Hambantota.", ru:"Спрессованные, упакованные и отправленные по всему миру из порта Хамбантота.", tr:"Sıkıştırılmış, paketlenmiş ve Hambantota Limanı'ndan dünya çapında sevk edilmiştir.", it:"Compressi, imballati e spediti in tutto il mondo dal Porto di Hambantota." },

  // Contact section
  "contact.desc": { en:"We'd love to hear about your growing needs. Reach out for product inquiries, custom orders, or to request samples.", ja:"栽培に関するご要望をお聞かせください。製品のお問い合わせ、カスタムオーダー、サンプルのご依頼など。", ar:"يسعدنا سماع احتياجاتك الزراعية. تواصل معنا للاستفسار عن المنتجات أو الطلبات المخصصة أو طلب عينات.", ko:"재배 요구 사항에 대해 듣고 싶습니다. 제품 문의, 맞춤 주문 또는 샘플 요청을 위해 연락하세요.", zh:"我们很乐意了解您的种植需求。产品咨询、定制订单或样品请求请联系我们。", nl:"We horen graag over uw teeltbehoeften. Neem contact op voor productvragen, maatwerkbestellingen of om monsters aan te vragen.", de:"Wir würden gerne von Ihren Anbaubedürfnissen hören. Kontaktieren Sie uns für Produktanfragen, Sonderbestellungen oder Musteranforderungen.", fr:"Nous aimerions connaître vos besoins de culture. Contactez-nous pour des demandes de produits, commandes sur mesure ou échantillons.", es:"Nos encantaría conocer sus necesidades de cultivo. Contáctenos para consultas de productos, pedidos personalizados o solicitar muestras.", ru:"Мы будем рады узнать о ваших потребностях в выращивании. Свяжитесь с нами для запросов о продукции, индивидуальных заказов или образцов.", tr:"Yetiştirme ihtiyaçlarınızı duymak isteriz. Ürün sorguları, özel siparişler veya numune talepleri için bize ulaşın.", it:"Ci piacerebbe conoscere le vostre esigenze di coltivazione. Contattateci per informazioni sui prodotti, ordini personalizzati o campioni." },
  "contact.email.label": { en:"Email", ja:"メール", ar:"البريد الإلكتروني", ko:"이메일", zh:"电子邮件", nl:"E-mail", de:"E-Mail", fr:"Email", es:"Correo", ru:"Электронная почта", tr:"E-posta", it:"Email" },
  "contact.location.label": { en:"Location", ja:"所在地", ar:"الموقع", ko:"위치", zh:"地址", nl:"Locatie", de:"Standort", fr:"Emplacement", es:"Ubicación", ru:"Местоположение", tr:"Konum", it:"Posizione" },
  "contact.website.label": { en:"Website", ja:"ウェブサイト", ar:"الموقع الإلكتروني", ko:"웹사이트", zh:"网站", nl:"Website", de:"Website", fr:"Site Web", es:"Sitio Web", ru:"Вебсайт", tr:"Web Sitesi", it:"Sito Web" },

  // CTA desc
  "cta.desc": { en:"Whether you need a sample shipment or a full container load, we're here to help your business flourish.", ja:"サンプル出荷からフルコンテナまで、お客様のビジネスの成長をお手伝いします。", ar:"سواء كنت بحاجة إلى شحنة عينات أو حمولة حاوية كاملة، نحن هنا لمساعدة عملك على الازدهار.", ko:"샘플 배송이든 풀 컨테이너든, 귀사의 비즈니스 성장을 도와드리겠습니다.", zh:"无论您需要样品还是整柜装载，我们都将助力您的业务蓬勃发展。", nl:"Of u nu een monster of een volledige container nodig heeft, wij helpen uw bedrijf groeien.", de:"Ob Musterlieferung oder volle Containerladung — wir helfen Ihrem Unternehmen zu wachsen.", fr:"Que vous ayez besoin d'un échantillon ou d'un conteneur complet, nous sommes là pour faire prospérer votre activité.", es:"Ya sea que necesite un envío de muestra o un contenedor completo, estamos aquí para ayudar a su negocio a prosperar.", ru:"Будь то пробная партия или полный контейнер — мы поможем вашему бизнесу расти.", tr:"İster numune sevkiyatı ister tam konteyner yükü olsun, işinizin büyümesine yardımcı olmak için buradayız.", it:"Che si tratti di un campione o di un container completo, siamo qui per far crescere il vostro business." }

};

window.CS_LANGUAGES = ['en','ja','ar','ko','zh','nl','de','fr','es','ru','tr','it'];

window.t = function(key, lang) {
  lang = lang || window._currentLang || 'en';
  var entry = window.TRANSLATIONS[key];
  if (!entry) return key;
  if (typeof entry === 'string') return entry;
  return entry[lang] || entry['en'] || key;
};

window._currentLang = localStorage.getItem('cs_lang') || 'en';
window.setLang = function(lang) {
  window._currentLang = lang;
  localStorage.setItem('cs_lang', lang);
  document.dispatchEvent(new CustomEvent('langchange', { detail: lang }));
};
